image: node:latest
 
cache:
  paths:
    - node_modules/
    - functions/node_modules/

test:
  stage: test
  script:
    - echo "Running tests"
    - npm run test

build:
  stage: build
  script:
    - echo "Building the app"
    - npm run build